const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// Public half of the Ed25519 keypair generated by
// scripts/license-admin/generate-keypair.js. This can verify license codes
// but — critically — cannot be used to forge new ones. Only the private key
// (kept solely on Nakano Tabasa's machine, never shipped in the installer)
// can sign a code the app will accept.
const PUBLIC_KEY_B64 = 'nyILyvRnYRxAhXahGEfhUGt+MkcDXzpJZhO4Qewi9tA=';
const ED25519_SPKI_PREFIX = Buffer.from('302a300506032b6570032100', 'hex');
const TRIAL_DAYS = 30;

function getPublicKeyObject() {
  const raw = Buffer.from(PUBLIC_KEY_B64, 'base64');
  const der = Buffer.concat([ED25519_SPKI_PREFIX, raw]);
  return crypto.createPublicKey({ key: der, format: 'der', type: 'spki' });
}

// Pure — no Electron dependency, so this can be unit-tested with plain node.
function verifySignedCode(code) {
  if (typeof code !== 'string') return { valid: false, reason: 'รูปแบบโค้ดไม่ถูกต้อง' };
  const trimmed = code.trim();
  const parts = trimmed.split('.');
  if (parts.length !== 2) return { valid: false, reason: 'รูปแบบโค้ดไม่ถูกต้อง' };

  const [payloadB64, sigB64] = parts;
  let payload;
  try {
    payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'));
  } catch {
    return { valid: false, reason: 'รูปแบบโค้ดไม่ถูกต้อง' };
  }

  let signatureOk;
  try {
    signatureOk = crypto.verify(
      null,
      Buffer.from(payloadB64),
      getPublicKeyObject(),
      Buffer.from(sigB64, 'base64url')
    );
  } catch {
    signatureOk = false;
  }

  if (!signatureOk) return { valid: false, reason: 'โค้ดนี้ไม่ถูกต้อง หรือถูกปลอมแปลง' };

  if (payload.exp !== null && Date.now() > payload.exp) {
    return { valid: false, reason: 'โค้ดนี้หมดอายุแล้ว', payload };
  }

  return { valid: true, payload };
}

// --- Electron-dependent storage (activation state + first-run trial clock) ---

function getStateStore() {
  const { app } = require('electron');
  const filePath = path.join(app.getPath('userData'), 'license-state.json');

  function load() {
    try {
      return JSON.parse(fs.readFileSync(filePath, 'utf8'));
    } catch {
      return {};
    }
  }

  function save(state) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, JSON.stringify(state, null, 2));
  }

  return { load, save };
}

function getStatus() {
  const store = getStateStore();
  const state = store.load();

  if (!state.firstRunAt) {
    state.firstRunAt = Date.now();
    store.save(state);
  }

  if (state.activatedCode) {
    const result = verifySignedCode(state.activatedCode);
    if (result.valid) {
      return {
        licensed: true,
        mode: result.payload.exp === null ? 'lifetime' : 'code',
        expiresAt: result.payload.exp,
        note: result.payload.note || null
      };
    }
    // Saved code is no longer valid (expired) — fall through to trial check,
    // the popup will explain the saved code expired.
  }

  const trialExpiresAt = state.firstRunAt + TRIAL_DAYS * 24 * 60 * 60 * 1000;
  const trialDaysLeft = Math.max(0, Math.ceil((trialExpiresAt - Date.now()) / (24 * 60 * 60 * 1000)));

  if (Date.now() < trialExpiresAt) {
    return { licensed: true, mode: 'trial', expiresAt: trialExpiresAt, trialDaysLeft };
  }

  return {
    licensed: false,
    mode: 'expired',
    expiresAt: trialExpiresAt,
    trialDaysLeft: 0,
    savedCodeExpired: Boolean(state.activatedCode)
  };
}

function activate(code) {
  const result = verifySignedCode(code);
  if (!result.valid) return { ok: false, reason: result.reason };

  const store = getStateStore();
  const state = store.load();
  state.activatedCode = code.trim();
  store.save(state);
  return { ok: true, mode: result.payload.exp === null ? 'lifetime' : 'code', expiresAt: result.payload.exp };
}

module.exports = { verifySignedCode, getStatus, activate, TRIAL_DAYS };
