const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dlchan', {
  appName: 'DL-chan',
  version: '0.3.0',
  pickFolder: () => ipcRenderer.invoke('download:pick-folder'),
  startDownload: (payload) => ipcRenderer.invoke('download:start', payload),
  listFormats: (url) => ipcRenderer.invoke('download:list-formats', url),
  isYtDlpUrl: (url) => ipcRenderer.invoke('download:is-ytdlp-url', url),
  pauseDownload: (id) => ipcRenderer.invoke('download:pause', id),
  resumeDownload: (id) => ipcRenderer.invoke('download:resume', id),
  cancelDownload: (id) => ipcRenderer.invoke('download:cancel', id),
  openInFolder: (destPath) => ipcRenderer.invoke('download:open-folder', destPath),
  openPath: (folderPath) => ipcRenderer.invoke('shell:open-path', folderPath),
  quitApp: () => ipcRenderer.invoke('app:quit'),
  setSpeedLimit: (kbps) => ipcRenderer.invoke('settings:set-speed-limit', kbps),
  setHlsEnabled: (enabled) => ipcRenderer.invoke('settings:set-hls-enabled', enabled),
  getLaunchOnStartup: () => ipcRenderer.invoke('settings:get-launch-on-startup'),
  setLaunchOnStartup: (enabled) => ipcRenderer.invoke('settings:set-launch-on-startup', enabled),
  openExtensionFolder: () => ipcRenderer.invoke('setup:open-extension-folder'),
  getExtensionPath: () => ipcRenderer.invoke('setup:get-extension-path'),
  getLicenseStatus: () => ipcRenderer.invoke('license:get-status'),
  activateLicense: (code) => ipcRenderer.invoke('license:activate', code),
  isLicenseAdminAvailable: () => ipcRenderer.invoke('license:admin-is-available'),
  generateGiftCode: (payload) => ipcRenderer.invoke('license:admin-generate-gift-code', payload),
  checkForUpdateNow: () => ipcRenderer.invoke('update:check-now'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  openUpdateDownload: (url) => ipcRenderer.invoke('update:open-download', url),
  onUpdateAvailable: (callback) => ipcRenderer.on('update:available', (event, data) => callback(data)),
  onUpdateDownloadProgress: (callback) => ipcRenderer.on('update:download-progress', (event, data) => callback(data)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update:downloaded', () => callback()),
  onUpdateError: (callback) => ipcRenderer.on('update:error', (event, data) => callback(data)),
  convertMedia: (payload) => ipcRenderer.invoke('media:convert', payload),
  onProgress: (callback) => ipcRenderer.on('download:progress', (event, data) => callback(data)),
  onError: (callback) => ipcRenderer.on('download:error', (event, data) => callback(data)),
  onDetected: (callback) => ipcRenderer.on('bridge:detected', (event, data) => callback(data)),
  onQueuedFromBrowser: (callback) => ipcRenderer.on('bridge:queued', (event, data) => callback(data)),
  onClipboardDetected: (callback) => ipcRenderer.on('clipboard:detected', (event, data) => callback(data))
});
